PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE asset (
    pid INTEGER, 
    download_id INTEGER, 
    asset_order INTEGER DEFAULT 0, 
    asset_type TEXT, 
    bytes_total INTEGER, 
    url TEXT, 
    local_path TEXT, 
    destination_url TEXT, 
    path_extension TEXT, 
    retry_count INTEGER, 
    http_method TEXT, 
    initial_odr_size INTEGER, 
    is_discretionary INTEGER DEFAULT 0, 
    is_downloaded INTEGER DEFAULT 0, 
    is_drm_free INTEGER DEFAULT 0, 
    is_external INTEGER DEFAULT 0, 
    is_hls INTEGER DEFAULT 0, 
    is_local_cache_server INTEGER DEFAULT 0, 
    is_zip_streamable INTEGER DEFAULT 0, 
    processing_types INTEGER DEFAULT 0, 
    video_dimensions TEXT, 
    timeout_interval REAL, 
    store_flavor TEXT, 
    download_token INTEGER DEFAULT 0, 
    blocked_reason INTEGER DEFAULT 0, 
    avfoundation_blocked INTEGER DEFAULT 0, 
    service_type INTEGER DEFAULT 0, 
    protection_type INTEGER DEFAULT 0,
    store_download_key TEXT, 
    etag TEXT, 
    bytes_to_hash INTEGER, 
    hash_type INTEGER DEFAULT 0, 
    server_guid TEXT, 
    file_protection TEXT, 
    variant_id TEXT, 
    hash_array BLOB, 
    http_headers BLOB, 
    request_parameters BLOB, 
    body_data BLOB, 
    body_data_file_path TEXT,
    sinfs_data BLOB, 
    dpinfo_data BLOB, 
    uncompressed_size INTEGER DEFAULT 0, 
    url_session_task_id INTEGER DEFAULT -1, 
    PRIMARY KEY (pid)
);
INSERT INTO asset VALUES(1,1,0,'media',0,'https://google.com',NULL,'/private/var/mobile/Media/iTunes_Control/iTunes/iTunesMetadata.plist','plist',0,'GET',0,0,0,0,0,0,0,0,0,NULL,0.0,NULL,0,0,0,0,0,NULL,NULL,0,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,-1);
INSERT INTO asset VALUES(2,1,0,'media',0,'https://google.com',NULL,'/private/var/containers/Shared/SystemGroup/GOODKEY/Documents/BLDatabaseManager/BLDatabaseManager.sqlite-wal','epub',0,'GET',0,0,0,0,0,0,0,0,0,NULL,0.0,NULL,0,0,0,0,0,NULL,NULL,0,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,-1);
INSERT INTO asset VALUES(3,1,0,'media',0,'https://google.com',NULL,'/private/var/containers/Shared/SystemGroup/GOODKEY/Documents/BLDatabaseManager/BLDatabaseManager.sqlite-shm','epub',0,'GET',0,0,0,0,0,0,0,0,0,NULL,0.0,NULL,0,0,0,0,0,NULL,NULL,0,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,-1);
INSERT INTO asset VALUES(4,1,0,'media',0,'https://google.com',NULL,'/private/var/containers/Shared/SystemGroup/GOODKEY/Documents/BLDatabaseManager/BLDatabaseManager.sqlite','epub',0,'GET',0,0,0,0,0,0,0,0,0,NULL,0.0,NULL,0,0,0,0,0,NULL,NULL,0,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,-1);
CREATE TABLE download (
    pid INTEGER, 
    state INTEGER DEFAULT 0, 
    dsid TEXT, 
    adam_id TEXT, 
    version_external_identifier TEXT, 
    external_purchase_id TEXT, 
    purchased_item_type TEXT, 
    kind TEXT, 
    artwork_sizes TEXT,
    artwork_token TEXT, 
    store_bundle_id TEXT, 
    store_front_id TEXT, 
    sort_order INTEGER DEFAULT 0, 
    priority INTEGER DEFAULT 0, 
    batch_order_id TEXT, 
    download_session_id TEXT, 
    download_queue_id TEXT, 
    is_free_download INTEGER DEFAULT 0, 
    is_redownload INTEGER DEFAULT 0, 
    is_stale INTEGER DEFAULT 0, 
    is_preorder INTEGER DEFAULT 0, 
    is_preorder_download INTEGER DEFAULT 0, 
    is_available_on_device INTEGER DEFAULT 0, 
    is_download_in_progress INTEGER DEFAULT 0, 
    is_stc_download INTEGER DEFAULT 0, 
    is_pre_delivery INTEGER DEFAULT 0, 
    download_type INTEGER DEFAULT 0, 
    is_subscription INTEGER DEFAULT 0, 
    subscription_external_id TEXT, 
    is_in_session INTEGER DEFAULT 0, 
    is_on_demand INTEGER DEFAULT 0, 
    odr_priority INTEGER DEFAULT 0, 
    started_by_application TEXT, 
    claimed_by_application TEXT, 
    claim_data BLOB, 
    PRIMARY KEY (pid)
);
INSERT INTO download VALUES(1,2,NULL,'BYPASS001','1.0.0','purchase001','media','ebook',NULL,NULL,'com.apple.iBooks','143441',0,5,NULL,NULL,NULL,0,0,0,0,0,1,1,0,0,0,0,NULL,0,0,0,'com.apple.BLDatabaseManager',NULL,NULL);
COMMIT;
